[package]
name = "vst-experiments"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"
vst = "0.2.1"

[lib]
name = "vst_experiments"
crate-type = ["cdylib"]
